c = 6.0
d = 9.0
print("This one multiplies")
print(c * d)
print("This one subtracts")
print(c - d)
print("This one raises to a power")
print(c ** d)
print("This one adds")
print(c + d)
print("This divides")
print(c / d)
print("This tells you how many times the first number goes into the first")
print(c // d)
print("This gives remainder")
print(c % d)
